### ISSUE TITLE
WP kan inte ansluta till JetPack

### ISSUE THREAD

**Issue by hmps** [swedish-football-network/sfn#2]
![jetpack sfn wordpress](https://f.cloud.github.com/assets/1231909/653175/05f216fa-d4cf-11e2-9a46-a2607b57e80a.jpg)

**Comment by hmps** [comment]
http://wordpress.org/support/topic/register_http_request_failed-2?replies=2#post-3746933

![wordpress support register_http_request_failed](https://f.cloud.github.com/assets/1231909/653177/12f837f8-d4cf-11e2-8cc7-328f7988fc0f.jpg)

**Comment by cheigert** [comment]
Det verkar som att våran server inte kan göra http requests utåt alls. Vi kan inte söka på teman heller vilket borde innebära att även vanliga http-requests ut från server sktier sig.

**Comment by cheigert** [comment]
Fixat! Om någon av er kan eller känner någon som kan iptables får ni gärna be dom kolla på det så jag inte har tabbat mig. Det finns script i /root/scripts/ som heter start.fw och stop.fw där startar och stoppar man brandväggen. I dessa script ska vi också lägga till de regler som vi lägga till senare.
